## Test Mainline NuttX every day for Ox64

name: Daily Test of NuttX for Ox64

permissions:
  ## Allow publishing of GitHub Release
  contents: write

on:

  ## Run every day at 1:00 UTC
  schedule:
    - cron: '0 1 * * *'

  ## Run on every commit to this branch
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Install Build Tools
      run:  |
        sudo apt -y update
        sudo apt -y install \
        expect libcurl4-openssl-dev libssl-dev zlib1g-dev libsdl2-dev wget

    - name: Checkout Source Files
      run:  |
        git clone https://github.com/lupyuen/ox64-tinyemu

    - name: Build TinyEMU
      run: |
        cd ox64-tinyemu
        make

    - name: Download NuttX Build
      run: |
        wget https://github.com/lupyuen/nuttx-ox64/releases/download/nuttx-ox64-${{ steps.date.outputs.date }}/nuttx.bin  

    - name: Run Test
      run: |
        ls -l nuttx.bin
        wget --output-document=nuttx.cfg https://raw.githubusercontent.com/lupyuen/nuttx-tinyemu/main/docs/root-riscv64.cfg
        ## wget --output-document=expect.sh https://raw.githubusercontent.com/lupyuen/nuttx-tinyemu/main/docs/root-riscv64.cfg
        ## chmod +x expect.sh
        ## ./expect.sh
